name: myplay
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  table_calendar: ^3.0.9
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  http: ^1.4.0
  uni_links: ^0.5.1
  inner_shadow_widget: ^0.0.2
  image_picker: ^1.0.7
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
    - family: 8bitWonder
      fonts:
        - asset: assets/fonts/8bit_wonder.ttf
    - family: PixeloidSans
      fonts:
        - asset: assets/fonts/PixeloidSans.ttf
        - asset: assets/fonts/PixeloidSans-Bold.ttf
          weight: 700
    - family: DungGeunMo
      fonts:
        - asset: assets/fonts/DungGeunMo.ttf
    - family: Galmuri14
      fonts:
        - asset: assets/fonts/Galmuri14.ttf
    - family: Spoqa Han Sans Neo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo-Light.ttf
          weight: 300 